# --- !Ups

create table account (
  id                        int generated by default as identity primary key,
  username                  varchar not null unique,
  password                  varchar not null,
  full_name                 varchar,
  is_admin                  boolean not null default false,
  email                     varchar not null unique,
  created_at                timestamp with time zone not null default now(),
  has_picture               boolean not null default false,
  description               varchar not null default '',
  check (username <> ''),
  check (password <> ''),
  check (email <> '')
);

create table repository (
  id                  int generated by default as identity primary key,
  owner_id            int not null references account(id),
  name                varchar not null,
  is_private          boolean not null default true,
  description         varchar not null default '',
  default_branch      varchar not null,
  created_at          timestamp with time zone not null default now(),
  main_file           varchar,
  unique (owner_id, name),
  check (name <> ''),
  check (default_branch <> ''),
  check (main_file <> '')
);

create table ssh_key (
  id                        int generated by default as identity primary key,
  account_id                int not null references account(id),
  public_key                varchar not null,
  created_at                timestamp with time zone not null default now(),
  check (public_key  <> '')
);

create table collaborator (
  id               int generated by default as identity primary key,
  account_id       int not null references account(id),
  repository_id    int not null references repository(id),
  role             smallint not null,
  created_at       timestamp with time zone not null default now(),
  unique (account_id, repository_id)
);

create index ssh_key_accountx ON ssh_key (account_id);

create index collaborator_account_idx ON collaborator (account_id);
create index collaborator_repo_idx ON collaborator (repository_id);

create index repository_owner_idx ON repository (owner_id);

# --- !Downs

drop table if exists collaborator, account, repository, ssh_key;

drop index if exists ssh_key_accountx;

drop index if exists collaborator_account_idx;
drop index if exists collaborator_repo_idx;

