os: linux
dist: xenial
language: scala

jobs:
  include:
    - stage: scalatest
      language: scala
      scala:
        - 2.13.1
      services:
        - postgresql
      before_script:
        - psql -c 'create database razam;' -U postgres
        - psql -c "create user razam with encrypted password 'razam';" -U postgres
        - psql -c "grant all privileges on database razam to razam;" -U postgres
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test
    - stage: frontend build
      language: node_js
      node_js: 12
      before_install: cd $TRAVIS_BUILD_DIR/frontend && npm install && npm install -g eclint
      script: eclint check "frontend/javascript/*.js" && cd $TRAVIS_BUILD_DIR/frontend && npm run build


cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local
