name: test_backend

on:
  push:
    branches:
    paths:
      - '.github/workflows/ci-test-backend.yml'
      - 'app/**'
      - 'conf/**'
      - 'project/**'
      - 'test/**'
  pull_request:
    branches:
    paths:
      - '.github/workflows/ci-test-backend.yml'
      - 'app/**'
      - 'conf/**'
      - 'project/**'
      - 'test/**'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: rzm
          POSTGRES_PASSWORD: rzm
          POSTGRES_USER: rzm
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Test and lint
      run: sbt scalafmtCheck test
